name: Daily POST Request SignIn

on:
  schedule:
    - cron: '1 4 * * *' # 上海时区中午12:30，

  workflow_dispatch:

jobs:
  read-config-file:
    runs-on: ubuntu-latest
    env:
      #Request SignIn
      URL: https://carbon-account-server.carbonstop.net/task/complete
      REQUEST_BODY: '{"value" : 1,"sceneCode" : "MRCJ0002","signMessage" : "2c2b34840b8ec9fb735e1b2bed8533fa"}'
      BARK_URL: 'https://api.day.app/oZaeqGLJzRLSxW7dJqeACn/'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Request SignIn
        run: |
          #!/bin/bash
          # Read the configuration file and process each line
          while IFS='=' read -r name token; do
            echo "Key: $name, Value: $token"
            echo "正在执行的账户: $name"
            curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization:$token" \
            -d "$REQUEST_BODY" \
            $URL \
            -o response.json
          
            echo "Response:"
            cat response.json
            # 检查响应内容
            if grep -q "token校验失败" response.json; then
              echo "$name token校验失败"
              # 发送Bark通知
              curl -X POST -H 'Content-Type: application/json' -d "{\"title\":\"碳账户Token失效通知\",\"body\":\"$name token校验失败\"}" "$BARK_URL"
            else
              echo "$name Token 可用"
              #curl -X POST -H 'Content-Type: application/json' -d "{\"title\":\"碳账户操作成功通知\",\"body\":\"$name token校验成功\"}" "$BARK_URL"
            fi

          done < config.properties
      - name: Log response status
        run: |
          RESPONSE_STATUS=$(jq -r '.status' response.json)
          echo -e "Response Status: $RESPONSE_STATUS \n"
