name: Daily POST Request Bike

on:
  schedule:
    - cron: '29 4 * * 1-5' # 上海时区中午12:29，

  workflow_dispatch:

jobs:
  read-config-file:
    runs-on: ubuntu-latest
    env:
      #Request Bike
      URL: https://carbon-account-server.carbonstop.net/task/complete
      REQUEST_BODY: '{"value" : 1,"sceneCode" : "MRCJ1888","signMessage" : "cb5632e24c8f83b157c910d6bb2bd525"}'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Request Bike
        run: |
          #!/bin/bash
          # Read the configuration file and process each line
          while IFS='=' read -r name token; do
            echo "Key: $name, Value: $token"
            echo "正在执行的账户: $name"
            curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization:$token" \
            -d "$REQUEST_BODY" \
            $URL \
            -o response.json
          
            echo "Response:"
            cat response.json  
          done < config.properties
      - name: Log response status
        run: |
          RESPONSE_STATUS=$(jq -r '.status' response.json)
          echo -e "Response Status: $RESPONSE_STATUS \n"
